### ISSUE TITLE
Game Objects are resorted when added to rename (2017.1)

### ISSUE THREAD

**Issue by Michal-MK** [redbluegames/unity-bulk-rename#109]
Rename setup - before pressing rename
[https://gyazo.com/77bd1f49c989cafb3a3a3818fa024c5e](url)

After pressing rename
[https://gyazo.com/77bd1f49c989cafb3a3a3818fa024c5e](url)

Edit: Downloaded latest version from releases, that fixed this problem, ReadMe "(Or click here)" contains outdated link ? 

Edit 2: A situation : 

![](https://i.gyazo.com/d5181884a0d26a8beb934f7d86f4f98f.png)

If I want to reverse the ordering of the objects, the app will just rearrange them in itself and doesn't rename anything. (I made this example for testing purposes)

**Comment by edwardrowe** [comment]
Thanks for the bug report!

About the first issue: The ReadMe does have an outdated link. I should remove that or maintain it properly ;) I'm real sorry about that.

I've renamed the subject of this Issue to reflect the bug you reported in the screenshot. That's something I've been meaning to do.
