### ISSUE TITLE
Integrate Spritesheet Renaming

### ISSUE THREAD

**Issue by edwardrowe** [redbluegames/unity-bulk-rename#26]
Currently sprites that are part of a spritesheet don't get renamed, since they are part of the metadata.

Could integrate this tool with this gist: https://gist.github.com/edwardrowe/1b18a5c8fd180733a68f

**Comment by edwardrowe** [comment]
We may actually need to extend this for all embedded assets? Could render them as a foldout.

**Comment by uvivagabond** [comment]
Its much harder then I expected.
I used TextureImported class and now I create version with SerializedObject (like in SpriteEditor) but always I lose references to renamed sprites when I use AssetDatabase.ImportAsset().  It's weird because in SpriteEditor, Unity also use this method to push changes in texture.
Now I try to change names only with metadata because it's propably only way.

**Comment by edwardrowe** [comment]
Yes, exactly. So frustrating. I found the metadata change to work but seems hacky. If you didn't see the gist that I'd written for this, you could leverage most of the code in there: https://gist.github.com/edwardrowe/1b18a5c8fd180733a68f

Might have a typo that /u/wkvs graciously pointed out.

**Comment by edwardrowe** [comment]
Oh and I believe this is where the changes are applied for Unity's Sprite Editor (you may have already found this as well). I think this also sheds light on why the meta files have the RecycleIDs in there.

https://github.com/MattRix/UnityDecompiled/blob/82e03c823811032fd970ffc9a75246e95c626502/UnityEditor/UnityEditor/SpriteEditorWindow.cs#L599

**Comment by edwardrowe** [comment]
They modify the properties by using SerializedProperties and then the use SerializableObject's ApplyModifiedPropertiesWithoutUndo(); to apply them.

https://github.com/MattRix/UnityDecompiled/blob/82e03c823811032fd970ffc9a75246e95c626502/UnityEditor/UnityEditor/SpriteEditorWindow.cs#L659

**Comment by edwardrowe** [comment]
This is merged in commit: 26687b8d877cbd2c12d06242d686359883a73af1

It modifies the text of the spritesheet to rename the sprites. It's been pushed to its own class, SpritesheetRenamer so that hopefully we can change out the algorithm if it doesn't match the way meta files are managed in the future.
