### ISSUE TITLE
Add Support for Sorting Selection

### ISSUE THREAD

**Issue by edwardrowe** [redbluegames/unity-bulk-rename#27]
Currently the selected items are renamed in essentially a random order. This makes enumerating particularly useless, since you often want the items to be named in a specific order.

Ideally it would respect the order items were selected. Alternatively, we could make the diff a reorderable list and let users rearrange them. That's not terrible useful if all items are named the same thing, though (ex: GameObject, GameObject, GameObject)

**Comment by uvivagabond** [comment]
In case of much different names I sugest checkbox to remove all names for all selected asset to give absolutely new names.

**Comment by uvivagabond** [comment]
When I use Trimming and Delete from back - there should be checkbox for equal deleting from back.
What I mean?
I have two names:
Cat(1)
Cat(111)
If I want to remove "111)" - I remove also "t(1)".

**Comment by edwardrowe** [comment]
In regards to the first comment - Debating about this. I see the use case, but I'm debating if using the Trimming feature addresses it enough. You could effectively just set your trim to the entire string. My concern is just a UI that's overly complex and scares users away. I'll think on it some more.

With regards to the second, you are right, trimming is not ideal there. I put in a feature for Regex search a while back, which I think is intuitive enough here. In your example a regex search string of "\(1+\)" would match the (1) and (111) suffixes.

![image](https://cloud.githubusercontent.com/assets/398377/24149636/9094e7b0-0e19-11e7-8f3c-bfca86a5ef31.png)

**Comment by uvivagabond** [comment]
Yes, easiest way is to change full name. 

In regards to the second part. 
Not everybody know Regex syntax. 
Look at your example.
Now I want to delete part from first "(" to the end of name.
Eastiest way now is two delete name and add new. There could be the option to handle that.

Maybe I should remind myself KISS :)

**Comment by edwardrowe** [comment]
I agree, Regex is far from user friendly. Most users of Unity probably don't even know what it is. That said, my main interest at the moment is to make sure most tasks are achievable with the tool. Then I want to make sure they are as easy as possible.

Some other alternatives to Regex:
I could provide a simple custom user syntax - maybe just * for wildcards. Then you'd use "(*)" for your example, but you wouldn't be able to ONLY grab 1's.

Another solution would be to provide a "Remove" section that lets users choose checkboxes like "Remove Symbols" "Remove Numbers" or "Remove custom characters" where users can put in their own lists of characters.

This could all be there in ADDITION to Regex as well, so that 'power' users could still use regex.

**Comment by uvivagabond** [comment]
Great idea.
