### ISSUE TITLE
Previews and Renaming fails on empty prefabs

### ISSUE THREAD

**Issue by edwardrowe** [redbluegames/unity-bulk-rename#32]
Reported by @uvivagabond. 

Empty prefabs don't report a name when using Object.Name. When selecting them, they increase the list of preview items but never get modified in the renaming process or displayed.

![problem with names](https://cloud.githubusercontent.com/assets/20247639/24199406/b2efb920-0f09-11e7-9830-d10c010e4379.png)

**Comment by uvivagabond** [comment]
I made few tests.
Empty prefab is type of UnityEngine.Object.
Object.name return:
1)For GameObject and Component - name of GameObject
2) For Assets Wrappers - name of Asset
3) For elements of type UnityEngine.Object its return NullReferenceException.

If we try set new name to element of type UnityEngine.Object also return NullReferenceException.
It's impossible to get/set name for UnityEngine.Object created in code.

**Comment by edwardrowe** [comment]
Awesome thanks for the info. 

As best as I can tell this only happens for those empty prefab objects. Unity rejects asset names that are blank. So in this commit: a5beb5c121e38af9fa4efd0f4598b26b0c144d5b I made it so that blank asset names are ignored (they don't count as a selection, and they don't show up in the list of assets).
