### ISSUE TITLE
Fill out Contributing file

### ISSUE THREAD

**Issue by lucasrowe** [redbluegames/unity-bulk-rename#78]
According to the [Github Community tab](https://github.com/redbluegames/unity-bulk-rename/community) we should have a couple more files to help the community use our tools.

1. Code of conduct file
1. Contributing file

For now let's focus on the Contributing file which will have the highest impact and is the easier of the two.

**Comment by edwardrowe** [comment]
I've added both of these documents. Contributing could be improved, which we can do over time.
