### ISSUE TITLE
Problem with sorting chosen items

### ISSUE THREAD

**Issue by uvivagabond** [redbluegames/unity-bulk-rename#82]
Items in window are no sorted by name.
![noorder](https://user-images.githubusercontent.com/20247639/27888539-d0099406-61e6-11e7-8167-951c7e366ab3.png)

**Comment by edwardrowe** [comment]
Thanks, yeah this is a nasty bug.

Objects within one selection group should obey Unity's native sort order, but selection groups should obey the order in which they are added into the renamer.

So if you select objects named A, B, F, G and add them, they should be in that order. If you then select a C and add it, the full list should be A, B, F, G, C.
