### ISSUE TITLE
Slider don't move

### ISSUE THREAD

**Issue by uvivagabond** [redbluegames/unity-bulk-rename#83]
When we mark more item then can be visible in window is showing slider, but it can't be move.
![slider not move](https://user-images.githubusercontent.com/20247639/27888595-32e31a48-61e7-11e7-9130-6224ddd1e01e.png)

**Comment by edwardrowe** [comment]
Ah huge bug! Good catch, thanks for submitting the issue.

**Comment by edwardrowe** [comment]
Fixed in latest (no submitted package, yet)
